var ability = {
	//Basic command ability
	'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero pse.',
	//
	'Endless Legions' : 'Choose a gravesite within 9\". You may pick a friendly <b>SUMMONABLE</b> unit that has been destroyed and set it up again wholly within 9\" of that gravesite and more than 9\" from any enemy models.',
	'The Unquiet Dead' : 'After territories have been determined, but before any units have been set up, you may pick up to 2 points in your territory and up to 2 points anywhere on the battlefield to be gravesites. You may wish to place suitable markers on these points. Instead of setting up a <b>SUMMONABLE</b> unit on the battlefield, you can place it to one side and say that it is set up in the grave. You can do this with as many units as you wish.<p>At the end of your movement phase, for each <b>DEATH HERO</b> within 9\" of a gravesite, you may pick a single unit in the grave and set it up wholly within 9" of that gravesite and more than 9\" from any enemy models. Any model that is unable to be set up in this way is slain. If a unit is still in the grave at the end of the battle, it is considered to be slain.</p><i>Gravesites have the following ability:</i><br><b>Invigorating Aura</b>: At the start of your hero phase, pick a friendly <b>SUMMONABLE</b> unit within 9\" of this gravesite. You can either heal D3 wounds that have been allocated to it or, if no wounds are currently allocated to the unit, you may return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
	'Deathless Minions' : 'Roll a dice each time you allocate a wound or mortal wound to a friendly <b>DEATH</b> unit within 6\" of your general or another friendly <b>DEATH HERO</b>. On a 6+ the wound is negated.',
	'Ethereal' : 'Ignore modifiers (positive or negative) when making save rolls for this model.',
	'FLY' : 'This unit can fly.',
}

var legions = {
	grandhostofnagash : {
		armyname : 'Grand Host of Nagash',
		commandability : {
			'Endless Legions' : '',
		},
		battletraits : {
			'The Unquiet Dead' : '',
			'Deathless Minions' : '',
			'Chosen Guardians' : '',
			'Legions Innumerable' : '',
		},
		commandtraits : {
			'Master of Death' : '',
			'Chosen Champion' : '',
			'Bane of the Living' : '',
			'Aura of Ages' : '',
			'Ancient Strategist' : '',
			'Lord of Nagashizzar' : '',
		},
		artefacts : {
			'Deathforged Chain' : '',
			'Balefire Lantern' : '',
			'Grave-sand Timeglass' : '',
			'Ossific Diadem' : '',
			'Amethyst Shard' : '',
			'Terrorgheist Mantle' : '',
		},
	},
	legionofsacrament : {
		armyname : 'Legion of Sacrament',
		commandability : {
			'Endless Legions' : '',
		},
		battletraits : {
			'The Unquiet Dead' : '',
			'Deathless Minions' : '',
			'The Master\'s Teachings' : 'Whenever an enemy unit is destroyed, before removing the last model, you may pick one of your gravesites within 6\" of that model.<br>Roll a dice, then remove the model.<br>On a 4+, you may pick a friendly <b>SUMMONABLE</b> unit that has been destroyed and set it up again wholly within 9\" of that gravesite and more than 9\" from any enemy models.',
			'The Black Disciples' : 'Friendly <b>LEGION OF SACRAMENT WIZARDS</b> may add 1 to casting rolls.',
		},
		commandtraits : {
			'Emissary of the Master' : 'You can re-roll failed charge rolls for friendly <b>DEATH</b> units that are within 6\" of this general at the start of the charge phase.',
			'Mark of the Favoured' : 'Each time this general is selected as the target of an attack in the combat phase, roll a dice. On a 6+ the attacking unit suffers a mortal wound.',
			'Dark Acolyte' : 'This general is a <b>WIZARD</b> that knows the Arcane Bolt and Mystic Shield spells, as well as a single spell from one of the Lores of the Dead.<br>If this general is already a <b>WIZARD</b>, they may generate an additional spell from one of the Lores of the Dead.',
			'Mastery of Death' : 'At the start of your hero phase, all friendly <b>DEATH</b> units within 6\" of this general may immediately make a move of up to 3\" as if it were your movement phase. They may not run as part of this move.',
			'Peerless Commander' : 'This general may summon a unit from a gravesite (see below) whilst they are within 12\" rather than 9\".',
			'Bound to the Master' : 'This general may use Arkhan the Black\'s First of the Mortarchs command ability (pg 97)',
			'* First of the Mortarchs' : 'Until the end of the hero phase all friendly <b>DEATH WIZARDS</b> within 18" of him can increase the range of their spells by 6\".',
		},
		artefacts : {
			'Spiritcage' : 'Whenever an enemy <b>HERO</b> is slain within 6\" of the bearer, add 1 to wound rolls for friendly <b>DEATH</b> units within 12\" of the bearer until the end of the turn.',
			'Shroud of Darkness' : 'Substract 1 from the hit rolls of attacks that target the bearer in the shooting phase if the attacking unit is within 8\" of the bearer.<br>Substract 2 from the hit rolls of attacks that target the bearer in the shooting phase if the attacking unit more than 8\" away from the bearer.',
			'Asylumaticae' : 'Once per battle, in your hero phase, you can declare that the bearer will open the Asylumaticae.<br>If you do so, roll a dice. On a 1 the bearer suffers a mortal wound. On a 2+ each enemy unit within 12\" of the bearer suffers 1 mortal wound.',
			'Wristbands of Black Gold' : 'Roll a dice each time you allocate a wound or mortal wound to the bearer in the shooting phase. On a 4+ the wound is negated.',
			'Azyrbane Standard' : 'Substract 1 from wound rolls for enemy units within 6\" of the bearer.<br>In addition, re-roll successful casting rolls for <b>ORDER WIZARDS</b> within 6\" of the bearer.',
			'Black Gem' : 'Once per battle, in your hero phase, you can declare that the bearer will shatter the Black Gem. Pick a point on the battlefield within 8\" of the bearer.<br>Roll a dice for each unit within 3\" of this point. On a 6+, one model from that unit is slain.<br>If the unit has any models with wounds allocated to it, then that model must be the model that is slain.',
		},
	},
	legionofblood : {
		armyname : 'Legion of Blood',
		commandability : {
			'Endless Legions' : '',
		},
		battletraits : {
			'The Unquiet Dead' : '',
			'Deathless Minions' : '',
			'Immortal Majesty' : '',
			'Favoured Retainers' : '',
		},
		commandtraits : {
			'Swift Strikes' : '',
			'Soul-crushing Contempt' : '',
			'Aristocracy of Blood' : '',
			'Aura of Dark Majesty' : '',
			'Walking Death' : '',
			'Sanguine Blur' : '',
		},
		artefacts : {
			'Ring of Dominion' : '',
			'Shadeglass Decanter' : '',
			'Orb of Enchantment' : '',
			'Soulbound Garments' : '',
			'Oubliette Arcana' : '',
			'Amulet of Screams' : '',
		},
	},
	legionofnight : {
		armyname : 'Legion of Night',
		commandability : {
			'Endless Legions' : '',
		},
		battletraits : {
			'The Unquiet Dead' : '',
			'Deathless Minions' : '',
			'The Bait' : '',
			'Ageless Cunning' : '',
		},
		commandtraits : {
			'Above Suspicion' : '',
			'Swift Form' : '',
			'Unbending Will' : '',
			'Merciless Hunter' : '',
			'Unholy Impetus' : '',
			'Terrifying Visage' : '',
		},
		artefacts : {
			'Vial of the Pure Blood' : '',
			'Shard of Night' : '',
			'Gem of Exsanguination' : '',
			'Chiropteric Cloak' : '',
			'Morbheg\'s Claw' : '',
			'Curseblade' : '',
		},
	},
	soulblight : {
		armyname : 'Allegiance: SOULBLIGHT',
		commandability : {
			'Inspiring Presence' : '',
		},
		battletraits : {
			'Deathless Thralls' : '',
			'The Bloodlines' : '',
			'* Dragon Warriors' : '',
			'* Lords of Night' : '',
			'* Necromantic' : '',
			'* Swift Death' : '',
		},
		commandtraits : {
			'Curse of the Revenant' : '',
			'Deathless Duelist' : '',
			'Transfix' : '',
			'Mist Form' : '',
			'Killing Blow' : '',
			'Blood Fury' : '',
		},
		artefacts : {
			'The Slaking Blade' : '',
			'The Scabbing Plate' : '',
			'Crimson Wing' : '',
			'Sigil of the Sanguine Throne' : '',
			'The Saccharine Goblet' : '',
			'Ruby Vail' : '',
		},
	},
	death : {
		armyname : 'Allegiance: DEATH',
		commandability : {
			'Inspiring Presence' : '',
		},
		battletraits : {
			'Deathless Minions' : '',
		},
		commandtraits : {
			'Ruler of the Night' : '',
			'Predator of the Shadows' : '',
			'Death Incarnate' : '',
			'Master of the Black Arts' : '',
			'Red Fury' : '',
		},
		artefacts : {
			'Cursed Book' : '',
			'Cloak of Mists and Shadows' : '',
			'Blade of Dark Summons' : '',
			'Black Amulet' : '',
			'Tomb Blade' : '',
			'Ring of Immortality' : '',
		},
	},
}

var magic = {
	lorebasic : {
		magicname : 'Basic spells',
		'Arcane Bolt' : {
			cast:'5',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'The unit you pick up suffers D3 mortal wounds.',
		},
		'Mystic Shield' : {
			cast:'6',
			range:'18 in LoS',
			target:'caster or friendly unit',
			effect:'You can add 1 to all save rolls for the unit you pick until the start of your next hero phase.',
		},
	},
	loreofdeathmages : {
		magicname : 'LORE OF THE DEATHMAGES',
		'OVERWHELMING DREAD' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
		'FADING VIGOUR' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
		'SPECTRAL GRASP' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
		'PRISON OF GRIEF' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
		'DECREPIFY' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
		'SOUL HARVEST' : {
			cast:'',
			range:'',
			target:'',
			effect:'',
		},
	},
	loreofvampires : {
		magicname : 'LORE OF THE VAMPIRES',
		'BLADES OF SHYISH' : {
			cast:'5',
			range:'( 12 )',
			target:'Each enemy unit',
			effect:'Roll a dice for each enemy unit within 12\" of the caster. On a 5+ that unit suffers 1 mortal wound.',
		},
		'SPIRIT GALE' : {
			cast:'6',
			range:'12 in LoS',
			target:'enemy unit',
			effect:'Roll 3D6. For each 5+, that unit suffers 1 mortal wound. In addition, if 2 of these dice show the same number, substract 1 from hit rolls for that unit until your next hero phase. If all 3 dice show the same number, substract 1 from hit and wound rolls for that unit until your next hero phase instead.',
		},
		'VILE TRANSFERENCE' : {
			cast:'7',
			range:'12 in LoS',
			target:'enemy unit',
			effect:'Pick an enemy unit within 12\" of the caster that is visible to them, and a friendly DEATH unit within 6" of that enemy unit. The enemy unit suffers D3 mortal wounds. Then, for each of these wounds that was allocatad and not negated, you can heal 1 wound allocated to the friendly unit.',
		},
		'AMETHYSTINE PINIONS' : {
			cast:'5',
			range:'self',
			target:'self',
			effect:'Until your next hero phase add 5\" to the caster\'s Move characteristic and the caster can fly.',
		},
		'SOULPIKE' : {
			cast:'6',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'Until your next hero phase, after a unit affected by any Soulpike spells makes a charge move, roll a number of dice equal to the result of their charge roll. For each 5+, that unit suffers 1 mortal wound.',
		},
		'AMARANTITE ORB' : {
			cast:'7',
			range:'12',
			target:'point',
			effect:'Pick a point on the battlefield within 12\" of the caster and draw an imaginary straight line 1mm wide between that point and the closest part of the caster. Roll a dice for each unit (friend or foe, apart from the caster) that has any models beneath this line. On a 4+ that unit suffers D6 mortal wounds.',
		},
	},
}

var units = {
	basic : {
		name:'NAME',
		role:'ROLE',
		move:'MOVE',
		wounds:'WOUNDS',
		bravery:'BRAVERY',
		save:'SAVE',
		points:'PTS',
		weapon : {
			'WEAPON_NAME_1' : {
				type:'TYPE',
				range:'RANGE',
				attacks:'ATTACKS',
				tohit:'TOHIT',
				towound:'TOWOUND',
				rend:'REND',
				damage:'DMG',
			},
			'WEAPON_NAME_2' : {
				type:'TYPE',
				range:'RANGE',
				attacks:'ATTACKS',
				tohit:'TOHIT',
				towound:'TOWOUND',
				rend:'REND',
				damage:'DMG',
			},
		},
		abilities : {
			'ABILITY_1' : 'ABILITY_1_TEXT',
			'ABILITY_2' : 'ABILITY_2_TEXT',
		},
		spell : {
			'Arcane Bolt' : {
				cast:'5',
				range:'18 in LoS',
				target:'enemy unit',
				effect:'The unit you pick up suffers D3 mortal wounds.',
			},
			'Mystic Shield' : {
				cast:'6',
				range:'18 in LoS',
				target:'caster or friendly unit',
				effect:'You can add 1 to all save rolls for the unit you pick until the start of your next hero phase.',
			},
		},
		command : {
			'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero pse.',
		},
		keywords:'KEYWORD_1, KEYWORD_2',
	},
	vampirelord : {
		name:'Vampire Lord',
		role:'Leader',
		move:'5 (10)',
		wounds:'5',
		bravery:'10',
		save:'4+',
		points:'140',
		weapon : {
			'Spirit-possesed Blades' : {
				type:'melee',
				range:'1',
				attacks:'4',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'D3',
			},
		},
		abilities : {
			'Flying Horror' : 'Vampire Lord with wings have Move 10" and can fly.',
			'Chalice of Blood' : 'Once per battle, in your hero phase, a Vampire Lord with a Chalice of Blood heals D6 wounds.',
			'The Hunger' : 'At the end of any combat phase in which this model slew any enemy models, you can heal 1 wound that has been allocated to it.',
			'Deathly Invocation' : 'At the start of your hero phase, pick up to 3 different friendly <b>SUMMONABLE</b> units within 12" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
			'Wizard' : 'Can attempt to cast one spell in each of your hero phases, and attempt to unbind one spell in each enemy hero phase.',
			},
		spell : {
			// 'Arcane Bolt (special)' : {
			// 	cast:'5',
			// 	range:'18 in LoS',
			// 	target:'enemy unit',
			// 	effect:'The unit you pick up suffers D3 mortal wounds.',
			// },
			// 'Mystic Shield (special)' : {
			// 	cast:'6',
			// 	range:'18 in LoS',
			// 	target:'caster or friendly unit',
			// 	effect:'You can add 1 to all save rolls for the unit you pick until the start of your next hero phase.',
			// },
		},
		command : {
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			'Blood Feast' : 'Pick a friendly <b>Death</b> unit within 15". Models in that unit make one extra attack with each of their melee weapons until your next hero phase.',
		},
		general : '1',
		keywords:'DEATH, LEGION, VAMPIRE, SOULBLIGHT, HERO, WIZARD, VAMPIRE LORD',
	},
	knightofshrouds : {
		name:'Knight of Shrouds',
		role:'Leader',
		move:'6',
		wounds:'5',
		bravery:'10',
		save:'4+',
		points:'120',
		weapon : {
			'Sword of Stolen Hours' : {
				type:'melee',
				range:'1',
				attacks:'4',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'2',
			},
		},
		abilities : {
			'FLY' : 'Knight of Shrouds can fly.',
			'Ethereal' : '',
			'Stolen Hours' : 'Each time a wound inflicted by this model\'s Sword of Stolen Hours slays an enemy <b>HERO</b>, heal 1 wound allocated to this model.',
			},
		command : {
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			'Spectral Overseer' : 'In the combat phase of this turn, add 1 to hit rolls for friendly <b>NIGHTHAUNT</b> models while they are within 9" of this model.',
		},
		general : '1',
		keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, KNIGHT OF SHROUDS',
	},
	wightking1 : {
		name:'Wight King (Tomb Blade)',
		role:'Leader',
		move:'4',
		wounds:'5',
		bravery:'10',
		save:'3+',
		points:'120',
		weapon : {
			'Baleful Tomb Blade' : {
				type:'melee',
				range:'1',
				attacks:'4',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'1',
			},
		},
		abilities : {
			'Beheading Strike' : 'If the wound roll for an attack made with a Baleful Tomb Blade is 6+, that attack has a Damage characteristic of D3.',
			'Deathly Invocation' : 'At the start of your hero phase, pick up to 2 different friendly <b>SUMMONABLE</b> units within 6" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
		},
		command : {
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			'Lord of Bones' : 'Pick a friendly <b>DEATHRATTLE</b> unit within 18". Until your next hero phase, add 1 to the Attacks characteristic of that unit\'s melee weapons.',
		},
		general : '1',
		keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, HERO, WIGHT KING',
	},
	wightking2 : {
		name:'Wight King (Black Axe)',
		role:'Leader',
		move:'4',
		wounds:'5',
		bravery:'10',
		save:'3+',
		points:'120',
		weapon : {
			'Black Axe' : {
				type:'melee',
				range:'1',
				attacks:'4',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'1',
			},
		},
		abilities : {
			'Black Axe' : 'If a model is allocated any wounds from attacks made using the Black Axe but is not slain, roll a dice after the Wight King has finished making all of its attacks. On a 6+ that model is slain.',
			'Barrow Armour' : 'Halve the number of wounds allocated to this model from each attack, rounding up (the remainder are negated).',
			'Deathly Invocation' : 'At the start of your hero phase, pick up to 2 different friendly <b>SUMMONABLE</b> units within 6" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
		},
		command : {
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			'Lord of Bones' : 'Pick a friendly <b>DEATHRATTLE</b> unit within 18". Until your next hero phase, add 1 to the Attacks characteristic of that unit\'s melee weapons.',
		},
		general : '1',
		keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, HERO, WIGHT KING',
	},
	tombbanshee : {
		name:'TOMB BANSHEE',
		role:'Leader',
		move:'6',
		wounds:'4',
		bravery:'10',
		save:'4+',
		points:'80',
		weapon : {
			'Ghostly Howl' : {
				type:'missile',
				range:'10',
				attacks:'1',
				tohit:'*',
				towound:'*',
				rend:'*',
				damage:'*',
			},
			'Chill Dagger' : {
				type:'melee',
				range:'1',
				attacks:'1',
				tohit:'4+',
				towound:'3+',
				rend:'-2',
				damage:'D3',
			},
		},
		abilities : {
			'FLY' : 'Tomb Banshee can fly.',
			'Ethereal' : '',
			'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Chill Dagger, that attack inflicts D3 mortal wounds instead of the normal damage (do not make a wound or save roll).',
			'Ghostly Howl' : 'When making a Ghostly Howl attack, pick a target within range, roll 2D6; if the total is higher than that unit\'s Bravery, it suffers a number of mortal wounds equal to the difference.',
			},
		command :{
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
		},
		keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, TOMB BANSHEE',
	},
	cairnwraith : {
		name:'CAIRN WRAITH',
		role:'Leader',
		move:'6',
		wounds:'4',
		bravery:'10',
		save:'4+',
		points:'60',
		weapon : {
			'Reaper Scythe' : {
				type:'melee',
				range:'2',
				attacks:'3',
				tohit:'4+',
				towound:'3+',
				rend:'-1',
				damage:'2',
			},
		},
		abilities : {
			'FLY' : 'Cairn Wraith can fly.',
			'Ethereal' : '',
			'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Reaper Scythe, that attack inflicts 2 mortal wounds instead of the normal damage.',
			'Reaped Like Corn' : 'If the target unit has 5 or more models, you can re-roll failed hit rolls for this model\'s Reaper Scythe.',
			},
		command : {
			// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
		},
		keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, CAIRN WRAITH',
	},

	hexwraiths : {
		name:'Hexwraiths (5-20)',
		role:'Battleline Nighthaunt',
		move:'12',
		wounds:'2',
		bravery:'10',
		save:'4+',
		points:'160',
		weapon : {
			'Hellwraith\'s Spectral Scythe' : {
				type:'melee',
				range:'1',
				attacks:'3',
				tohit:'4+',
				towound:'3+',
				rend:'-1',
				damage:'1',
			},
			'Spectral Scythe' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'3+',
				rend:'-1',
				damage:'1',
			},
			'Skeletal Steed\'s Hooves and Teeth' : {
				type:'melee',
				range:'1',
				attacks:'3',
				tohit:'4+',
				towound:'5+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'HELLWRAITH' : 'The leader of this unit is Hellwraith. Add 1 to the Attacks characteristic of a Hellwraith\'s Spectral Scythe.',
			'FLY' : 'Hexwraiths can fly.',
			'Ethereal' : '',
			'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Spectral Scythe, that attack inflicts 1 mortal wound instead of the normal damage (do not make a wound or save roll).',
			'Spectrum Hunter\'s' : 'In the movement phase, immediately after this unit has moved, you can pick an enemy unit that was passed across by any models from this unit. If you do so, roll a dice for each Hexwraith that passed across that enemy unit. For each roll of 5+, that enemy unit suffers 1 mortal wound.',
			},
		keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, SUMMONABLE, HEXWRAITHS',
	},
	spirithosts : {
		name:'Spirit Hosts (3-12)',
		role:'Battleline Nighthaunt',
		move:'6',
		wounds:'3',
		bravery:'10',
		save:'4+',
		points:'120',
		weapon : {
			'Spectral Claws and Daggers' : {
				type:'melee',
				range:'1',
				attacks:'6',
				tohit:'5+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Spirit Hosts can fly.',
			'Ethereal' : '',
			'Frightful Touch' : 'If the hit roll for an attack made by a Spirit Host is 6+, immediately inflict 1 mortal wound instead of its normal damage.',
			},
		keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, SUMMONABLE, SPIRIT HOSTS',
	},

	mortisengine : {
		name:'Mortis Engine',
		role:'Behemoth',
		move:'14 | 12 | 10 | 8 | 4',
		wounds:'2|3-4|5-7|8-9|10-12',
		bravery:'10',
		save:'4+',
		points:'180',
				/*
		degradation table
		wailrg attacks move dmg
		9		12 		14 	0-2
		8		10 		12 	3-4
		7		8 		10 	5-7
		6		6 		8 	8-9
		5		4 		4 	10+
				*/
		weapon : {
			'Wail of the Damned' : {
				/*see below*/
				type:'missile',
				range:'9 | 8 | 7 | 6 | 5',
				attacks:'*',
				tohit:'*',
				towound:'*',
				rend:'*',
				damage:'*',
			},
			'Corpsemaster\'s Mortis Staff' : {
				type:'melee',
				range:'1',
				attacks:'1',
				tohit:'4+',
				towound:'3+',
				rend:'-1',
				damage:'D3',
			},
			'Spectral Host\'s Ethereal Weapons' : {
				type:'melee',
				range:'1',
				attacks:'12 | 10 | 8 | 6 | 4',
				tohit:'5+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Mortis Engines can fly.',
			'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Spectral Host\'s Ethereal Weapons, that attack inflicts 1 mortal wound instead of the normal damage (do not make a wound or save roll).',
			'Wail of the Damned' : 'When making a Wail of the Damned attack, roll 2D6 for each enemy unit within the range shown on the damage table. If the total is higher than that unit\'s Bravery, it suffers D3 mortal wounds.',
			'The Reliquary' : 'Once per battle, in hero phase roll 4D6. Each unit within that many inches affected. <b>Death</b> units heal D3 wounds, but any other unit suffers D3 mortal wounds.',
			'Bound Necromancer' : 'Add 1 to casting rolls for Death Wizards within 12" of any Mortis Engines. Substract 1 from casting rolls for Order, Destruction and Chaos Wizards within 12" of any Mortis Engines.',
			},
		keywords:'DEATH, LEGION, MALIGNANT, DEATHMAGES, MORTIS ENGINE',
	},
	sepulcharguard : {
		name:'THE SEPULCHAR GUARD',
		role:'',
		move:'4',
		wounds:'1',
		bravery:'10',
		save:'6+',
		points:'80',
		weapon : {
			'Sepulchar Warden\'s Ancient Spear' : {
				type:'melee',
				range:'2',
				attacks:'3',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
			'Petitioner\'s Ancient Blade (3)' : {
				type:'melee',
				range:'1',
				attacks:'1 (3)',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
			'Champion\'s Ancient Greatblade' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'4+',
				rend:'-1',
				damage:'1',
			},
			'Prince\'s of Dust Ancient Mace' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'3+',
				rend:'-',
				damage:'1',
			},
			'Harvester\'s Ancient Scythe' : {
				type:'melee',
				range:'1',
				attacks:'1',
				tohit:'4+',
				towound:'3+',
				rend:'-',
				damage:'2',
			},
		},
		abilities : {
			'Crypt Shield' : 'Models with Crypt Shield can add +1 to save rolls against attacks with Rend of -',
			'Serve in Death' : 'You can add 1 to hit rolls for this unit if it is wholly within 18" of any friendly <b>Death Heroes</b>.',
			'Frightening Speed' : 'You can re-roll charge rolls for this unit.',
			'The Sepulchar Warden' : 'In each of your hero phases you can return D3 slain models to this init while the Sepulchar Warden is on the battlefield.',
			'unique' : 'Only one of this unit can be included in a Pitched Battle army.',
		},
		keywords:'DEATH, SKELETON, DEATHRATTLE, SKELETON WARRIORS, THE SEPULCHAR GUARD',
	},
	batswarms : {
		name:'Bat Swarms (2-8)',
		role:'',
		move:'12',
		wounds:'5',
		bravery:'10',
		save:'-',
		points:'80',
		weapon : {
			'Razor-sharp Teeth' : {
				type:'melee',
				range:'3',
				attacks:'5',
				tohit:'5+',
				towound:'5+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Bat Swarms can fly.',
			'Cloud of Horror' : 'Substract 1 from hit rolls for enemy units that are within 12" of any Bat Swarms in the Shooting phase.',
			'Blood Suckers' : 'At the end of any combat phase in which this unit caused any wounds to be allocated to any enemy models, you can heal all wounds that have been allocated to this unit.',
			},
		keywords:'DEATH, LEGION, SOULBLIGHT, SUMMONABLE, BAT SWARMS',
	},
	fellbats : {
		name:'Fell Bats (3-12)',
		role:'',
		move:'14',
		wounds:'3',
		bravery:'10',
		save:'6+',
		points:'80',
		weapon : {
			'Elongated Fangs' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Bat Swarms can fly.',
			'Scent of Gore' : 'If an enemy model is slain within 6" of this unit, increase the Attacks characteristic of this unit\'s Elongated Fangs to 6 for the rest of the battle.',
			},
		keywords:'DEATH, LEGION, SOULBLIGHT, SUMMONABLE, FELL BATS',
	},
}